### PR TITLE
Minor corrections for the addons.html page

### PR DESCRIPTION
**Pull request by iMezouar**
Corrected some small mistakes in the addons.html page text

### CODE REVIEW

**Comment by iMezouar** [comment]
Didn't see that user ExcaliburZero has already submitted much the same corrections to the addons.html page. I'm closing this.

**Comment by iMezouar** [comment]
I reopened this because the other similar pull request (by ExcaliburZero) seems to be removed.

**Comment by ExcaliburZero** [comment]
The pull request I set up should still be there. #132

**Comment by iMezouar** [comment]
Indeed it is still there, I couldn't find it when searching for pull requests made by you. Thanks.

**Pull request closed without merging**
