### PR TITLE
Several sunxi fixes, better documentation

### PR DESCRIPTION
**Pull request by ThomasKaiser**
Feature freeze. Based on some feedback I improved documentation and code for the sunxi relevant stuff. Ready for 2.11 :-)

BTW: The stuff regarding USB disks might be worth a look to include in a separate RPi related config?

### CODE REVIEW

**Comment by XavierBerger** [comment]
Hi Thomas, I do prefer no doing development in master branch. The devel branch is dedicated for such purpose. I did a merge for your last pull request and I had to merge master to devel.
Can you propose a pull request for devel branch. You can just merge you master in your devel branch then propose a pull request.

**Comment by ThomasKaiser** [comment]
Sorry, I'm completely new to git/github and it seems I have to do some homework first. This does not look good to me: https://github.com/XavierBerger/RPi-Monitor/compare/devel...ThomasKaiser:devel

**Comment by XavierBerger** [comment]
Here are the commands to execute to propose a pull request in devel branch:
1/ Change active branche
git checkout devel
2/ Merge modification done in master into devel branch  
git merge master devel
3/ push you change on github
4/ Select the branch devel and do the normal process to propose a pull request.

**Comment by dschaper** [comment]
Is the SunXI addition still being actively developed?

**Comment by XavierBerger** [comment]
This pull request is on master branch which is supposed to only have stable (and released) version.
I'll then integrate this pull request when I'll publish the next release. 
Unfortunately, next release is not planned soon since I've not too much time to spend on RPi-Monitor...

**Comment by dschaper** [comment]
If the original author doesn't mind, I can make the changes on my fork of devel and send a new pull request... I have an H3 based Orange Pi 2 I can test on.

**Comment by XavierBerger** [comment]
dschaper create a pull request #130 to merge these change on devel branch.

**Pull request closed without merging**
